using UnityEngine;

public class READFIRST : MonoBehaviour
{
    /*
     * HI GUYS SO THIS IS A RAWDOGGED VERSION OF THE TUTORIALS. 
     * BUT MANY OF THE MODULAR SHT IS BASED OF THIS ONE
     * WHATEVER YOU DO, DO NOT ATTEMPT TO MAKE ANY CHANGES IN 
     * THESE SCRIPPTS BECAUSE IT MIGHT DISRUPT THE FLOW
     * OF THE TUTORIAL AND I WILL CRY <3
     * 
     * I MEAN FEEL FREE TO ADD ANYTHING BUT DO NOT OVERHAUL IT
     * ESPECIALLY THE STRUCT. DO N O T REMOVE ANYTHING AT ALL.
     * PLEASE
     * 
     * THANKS!
     */
}
